livecode/gardens-and-plants-447/config/routes.rb
Rails.application.routes.draw do
  root to: "gardens#index"

  # 7 crud actions (i can view all, one, create, update and delete)
  resources :gardens do
    # that it's gonna have gardens/:garden_id/plants/new [GET]
    # that it's gonna have gardens/:garden_id/plants [POST]
    resources :plants, only: [:new, :create]
  end

  # I prefer plants/:id [GET]
  # than gardens/:garden_id/plants/:id [GET]

  resources :plants, only: [:show, :destroy] do
    resources :plant_tags, only: :create
  end

  # resources :plant_tags, only: :create


  resources :tags, only: [:index, :new, :create]
end

livecode/gardens-and-plants-447/app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

livecode/gardens-and-plants-447/app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, :image_url, presence: true
end

livecode/gardens-and-plants-447/app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :plant, uniqueness: { scope: :tag }
end

livecode/gardens-and-plants-447/app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags
end

livecode/gardens-and-plants-447/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

livecode/gardens-and-plants-447/app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    @gardens = Garden.all
  end

  def show
  end

  def new
    @garden = Garden.new
  end

  def edit
  end

  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

livecode/gardens-and-plants-447/app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController

  def create
    @plant_tag = PlantTag.new(plant_tag_params)
    @plant_tag.plant_id = params[:plant_id]

    if @plant_tag.save
      redirect_to garden_path(@plant_tag.plant.garden)
    else
      render 'plants/show'
    end
  end

  private
  def plant_tag_params
    params.require(:plant_tag).permit(:tag_id)
  end

end

livecode/gardens-and-plants-447/app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def show
    @plant = Plant.find(params[:id])
  end


  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to @garden
    else
      render :new
    end
  end

  # DELETE /plants/4
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

livecode/gardens-and-plants-447/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  # page with the form
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path
    else
      render :new
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

livecode/gardens-and-plants-447/app/helpers/gardens_helper.rb
module GardensHelper
end

livecode/gardens-and-plants-447/app/helpers/plants_helper.rb
module PlantsHelper
end

livecode/gardens-and-plants-447/app/views/gardens/_form.html.erb
<%= form_with(model: garden, local: true) do |form| %>
  <% if garden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garden.errors.count, "error") %> prohibited this garden from being saved:</h2>

      <ul>
        <% garden.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :banner_url %>
    <%= form.text_field :banner_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

livecode/gardens-and-plants-447/app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

livecode/gardens-and-plants-447/app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

livecode/gardens-and-plants-447/app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

livecode/gardens-and-plants-447/app/views/gardens/show.html.erb
<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-3">
        <div class="plant-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
          <%= link_to plant.name, plant_path(plant) %>
          <%= link_to "x", plant_path(plant), method: :delete, class: "card-remove-link"  %>
        </div>
      </div>
    <% end %>
    <div class="col-3">
      <%= link_to "Add plant", new_garden_plant_path(@garden) %>
    </div>
  </div>
</div>

livecode/gardens-and-plants-447/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

livecode/gardens-and-plants-447/app/views/plants/new.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h1>New plant for <%= @garden.name %></h1>
    <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name, placeholder: "Palm tree" %>
      <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

livecode/gardens-and-plants-447/app/views/plants/show.html.erb
<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @plant.garden.banner_url %>);">
  <div class="container">
    <h1><%= @plant.garden.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="plant-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @plant.image_url %>)">
        <%= @plant.name %>
      </div>
      <ul>
        <% @plant.tags.each do |tag| %>
          <li><%= tag.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= simple_form_for [@plant, PlantTag.new] do |f| %>
  <%= f.association :tag %>
  <%= f.submit "Tag this plant!" %>
<% end %>

livecode/gardens-and-plants-447/app/views/tags/index.html.erb
<ul>
  <% @tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
</ul>

livecode/gardens-and-plants-447/app/views/tags/new.html.erb
<%= simple_form_for @tag do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save" %>
<% end %>